---
title: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

### BDEF richness reverse causation synthesis
An exploration of richness as both driver and response in plant facilitation studies.  

### PRISMA
Review process.

```{r}
library(PRISMAstatement)

#Search from Web of Science updated Aug 2020: positive, facilitat*, shrub 

prisma(found = 593,
       found_other = 20,
       no_dupes = 613, 
       screened = 613, 
       screen_exclusions = 0, 
       full_text = 613,
       full_text_exclusions = 310, 
       qualitative = 19, 
       quantitative = 19,
       width = 600, height = 600)

#a total of 19 studies comprising 141 independent observations

```


#### Data
```{r}
library(tidyverse)
#library(gsheet)
#data <- gsheet2tbl('docs.google.com/spreadsheets/d/1B6XudNqvx2kSjAB_l0plfrzyG0o6vuAsDxtwSVeBP3c')
#write_csv(data, "data/diversity.csv")
data <- read_csv("data/diversity.csv")

#tidy data
data <- data %>% 
  mutate(rii_calc = (shrub-open)/(shrub + open)) %>%
  filter(!is.na(n)) %>%
  filter(!is.na(rii_calc)) %>%
  mutate(lat = as.numeric(lat), n = as.numeric(n)) %>%
  mutate(var.es = (shrub_error/(sqrt(n)))) %>%
  filter(var.es > 0) %>% 
  filter(!is.na(simplified_response))

```


#### Viz
```{r}
ggplot(data, aes(n_species, rii_calc)) +
  geom_point(aes(size = var.es, color = design), show_guide = FALSE) +
  geom_smooth(method = lm, se = FALSE, color = "dodgerblue3", size = 2) +
  scale_color_brewer(palette = "Paired") +
  labs(x = "total number of plant species", y = "rii diversity")

ggplot(data, aes(n_species, rii_calc)) +
  geom_point(aes(size = var.es), show_guide = FALSE) +
  geom_smooth(method = lm, se = FALSE, color = "black", size = 2) +
  scale_color_brewer(palette = "Paired") +
  labs(x = "total number of plant species", y = "rii diversity") +
  geom_hline(yintercept = 0, linetype = 2, colour = "red", size = 1) +
  ylim(-1,1) +
  xlim(0,80)


#ggplot(data, aes(n_species, rii_calc, color = design)) +
  #geom_point() +
  #geom_smooth(method = lm)

```

#### Metamodels
```{r}
library(meta)
library(metafor)
m1.1 <- metagen(rii_calc, var.es, comb.fixed = FALSE, data = data)
summary(m1.1)
#metabias(m1.1)

m1.2 <- metareg(m1.1, ~n_species)
plot(m1.2)
summary(m1.2)
bubble(m1.2)

m1.3 <- metareg(m1.1, ~ poly(n_species,2))
plot(m1.3)
summary(m1.3)
#bubble(m1.3)

anova(m1.2, m1.3) #to explore linear versus polynomial models
permutest(m1.3) #to explore robuestness of model, ie. if cofficients are a relatively true representation of the variation in the estimate pattern in data

#moderators
m2.1 <- metareg(m1.1, ~n_species*design)
summary(m2.1) #observational key

m2.2 <- metareg(m1.1, ~n_species*protege_pfg)
summary(m2.2) #no differences

m2.3 <- metareg(m1.1, ~n_species*response)
summary(m2.3) #no meaningful difference between key measures such as richess or evenness

```

